name: api-build-deploy

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - FoodApi

trigger: none

variables:
  dotnetSdkVersion: "5.x"
  buildConfiguration: Release
  releaseBranchName: master
  azSubscription: scMVCDevOps
  appfolder: skills-mvc
  appservice: mvc-devops-skills
  envflag: staging

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: Build
    displayName: Build and Provision
    jobs:
      - job: Build

        steps:
          - template: templates/netcore-build.yaml
            parameters:
              cfg: $(buildConfiguration)
              folder: $(appfolder)

      - job: Test
        displayName: "Unit Test"

        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: "test"
              projects: "skills-test/*.csproj"
              arguments: "--configuration $(buildConfiguration)"              
      
      - job: Provision

        steps:
        
        - task: AzureCLI@2
          displayName: 'Provision AppService'
          inputs:
            azureSubscription: '$(azSubscription)'
            scriptType: 'bash'
            scriptLocation: 'scriptPath'
            scriptPath: '$(System.DefaultWorkingDirectory)/az-cli/create-appservice.sh'
            arguments: '$(envflag)'


  - stage: Deploy
    displayName: Deploy
    dependsOn: Build

    jobs:
      - deployment: DeployAppService
        displayName: Deploy to Appservice
        environment: $(envflag)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: "current"
                    downloadType: "single"
                    artifactName: "drop"
                    downloadPath: "$(System.ArtifactsDirectory)"

                - task: AzureRmWebAppDeployment@4
                  displayName: "Azure App Service Deploy: $(appservice)"
                  inputs:
                    ConnectionType: "AzureRM"
                    azureSubscription: $(azSubscription)
                    appType: "webApp"
                    WebAppName: "$(appservice)-$(envflag)"
                    packageForLinux: "$(System.ArtifactsDirectory)/**/*.zip"
