name: api-build-deploy

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - FoodApi

trigger: none

variables:
  dotnetSdkVersion: "5.x"
  buildConfiguration: Release
  releaseBranchName: master
  azSubscription: scMVCDevOps
  appfolder: skills-mvc
  appservice: mvc-devops-skills
  envflag: staging

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: Build
    displayName: Build and Provision
    jobs:
      - job: Build

        steps:
          - template: templates/netcore-build.yaml
            parameters:
              cfg: $(buildConfiguration)
              folder: $(appfolder)

      - job: Test
        displayName: "Unit Test"

        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: "test"
              projects: "skills-unittest/*.csproj"
              arguments: "--configuration $(buildConfiguration)"              

  - stage: Selenium
    displayName: Run Selenium Tests
    dependsOn: Build

    jobs:
      - deployment: DeployAppService
        displayName: Deploy to Appservice
        environment: $(envflag)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: "current"
                    downloadType: "single"
                    artifactName: "drop"
                    downloadPath: "$(System.ArtifactsDirectory)"

                - task: AzureRmWebAppDeployment@4
                  displayName: "Azure App Service Deploy: $(appservice)"
                  inputs:
                    ConnectionType: "AzureRM"
                    azureSubscription: $(azSubscription)
                    appType: "webApp"
                    WebAppName: "$(appservice)-$(envflag)"
                    packageForLinux: "$(System.ArtifactsDirectory)/**/*.zip"
                    
                
      - job: RunUITests
        dependsOn: DeployAppService
        displayName: 'Run UI tests'
        pool:
          vmImage: 'windows-2019'
        variables:
        - group: 'Release'
        steps: 
        - task: UseDotNet@2
          displayName: 'Use .NET SDK $(dotnetSdkVersion)'
          inputs:
            version: '$(dotnetSdkVersion)'
        - task: DotNetCoreCLI@2
          displayName: 'Build the project - $(buildConfiguration)'
          inputs:
            command: 'build'
            arguments: '--configuration $(buildConfiguration)'
            projects: '$(System.DefaultWorkingDirectory)/**/*skills-selenium.tests.csproj'
        - task: DotNetCoreCLI@2
          displayName: 'Run unit tests - $(buildConfiguration)'
          inputs:
            command: 'test'
            arguments: '--no-build --configuration $(buildConfiguration)'
            publishTestResults: true
            projects: '$(System.DefaultWorkingDirectory)/**/*skills-selenium.tests.csproj'
