name: mvc-ci-template

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - skills-mvc

trigger: none

variables:
  dotnetSdkVersion: "6.x"
  buildConfiguration: Release
  appfolder: skills-mvc

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: Build
    displayName: Build MVC
    jobs:
      - job: Build
        steps:
            - task: UseDotNet@2
              displayName: "Use .NET Core SDK $(dotnetSdkVersion)"
              inputs:
                version: "$(dotnetSdkVersion)"

            - task: DotNetCoreCLI@2
              displayName: "Restore project dependencies"
              inputs:
                command: "restore"
                projects: "$(appfolder)/*.csproj"

            - task: DotNetCoreCLI@2
              displayName: "Build the project - $(buildConfiguration)"
              inputs:
                command: "build"
                arguments: "--no-restore --configuration $(buildConfiguration)"
                projects: "$(appfolder)/*.csproj"

            - task: DotNetCoreCLI@2
              displayName: "Publish the project - $(buildConfiguration)"
              inputs:
                command: "publish"
                projects: "$(appfolder)/*.csproj"
                publishWebProjects: false
                arguments: "--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)"
                zipAfterPublish: true
                
            - task: PublishPipelineArtifact@1
              inputs:
                targetPath: '$(Pipeline.Workspace)'
                artifact: 'mvcapp'
                publishLocation: 'pipeline'